### ISSUE TITLE
[FE-BUG] :Datepicker  밑부분 UI 짤림 현상

### ISSUE THREAD

**Issue by taejinii** [puppypawpaw/pawpaw-client#50]
## Description
기능에 어떤 버그가 있는지 알려주세요.

작은 화면에서 Datepicker 밑부분이 잘려보이는 현상 발생
기타 CSS 수정

## Steps to Reproduce
원래 의도한 동작은 무엇이었는지 설명해주세요.

1. Datepicker 의 UI가 잘림현상없이 렌더링 되어야 한다.
2. 버튼 클릭시 primary-100 적용된것을 삭제

## ScreenShot
버그에 대한 스크린샷을 남겨주세요.  

<img width="1422" alt="image" src="https://github.com/puppypawpaw/pawpaw-client/assets/96623949/b6c78725-b54f-499c-adc1-c6c1bfac6f03">

##  ETC 
추가사항이 있다면 남겨주세요.

**Comment by shseok** [comment]
![image](https://github.com/puppypawpaw/pawpaw-client/assets/80726955/c5e127ea-46d4-4621-8c50-8dd9176309d4)

현재 반응형으로 적용했을 때 또한 약간의 문제가 있는 것 같습니다.

768px 이하부터 시작 및 종료 날짜 별 DatePicker와 TimeSelect 컴포넌트는 1줄에 1개씩 위치해야 할 것 같습니다.
즉, 768px 이하 크기에서 시작/종료 날짜에 2개의 컴포넌트씩 배치하면 해결 될 것 같습니다.

**Comment by taejinii** [comment]
> ![image](https://user-images.githubusercontent.com/80726955/267927404-c5e127ea-46d4-4621-8c50-8dd9176309d4.png)
> 
> 현재 반응형으로 적용했을 때 또한 약간의 문제가 있는 것 같습니다.
> 
> 768px 이하부터 시작 및 종료 날짜 별 DatePicker와 TimeSelect 컴포넌트는 1줄에 1개씩 위치해야 할 것 같습니다. 즉, 768px 이하 크기에서 시작/종료 날짜에 2개의 컴포넌트씩 배치하면 해결 될 것 같습니다.

확인했습니다!
